---
driver:
  name: ec2
  instance_type: m1.small
  aws_ssh_key_id: my-dev-key
  region: us-west-2
  availability_zone: us-west-2b
  subnet_filter:
    tag:   'Name'
    value: 'Config Mgmt Testing'
  associate_public_ip: false
  interface: private
  security_group_filter:
    tag:   'Name'
    value: 'Config Mgmt Testing'
  tags:
    Name: tk-ansible-role-realm-object-server
    Created-By: Test Kitchen

platforms:
  - name: centos
    driver:
      name: docker
    driver_config:
      run_command: /usr/sbin/init
      privileged: true
      image: centos/systemd
      provision_command:
        - yum -y install net-tools
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
  - name: amazonlinux-2-docker
    driver:
      name: docker
    driver_config:
      platform: rhel
      run_command: /usr/sbin/init
      privileged: true
      image: amazonlinux:2
      # Apply workaround in that the ps command is not working out of the box
      # on Amazon Linux 2 Docker containers
      provision_command:
        - yum -y install procps-ng net-tools
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
  - name: amazonlinux-2-ec2
    driver:
      name: ec2
    driver_config:
      image_id: ami-8f08bcf7
    transport:
      username: ec2-user
      ssh_key: ~/my-dev-key.pem

provisioner:
  name: ansible_playbook
  hosts: localhost
  ansible_verbose: false
  ansible_verbosity: :debug
  require_chef_for_busser: false
  require_ruby_for_busser: false
  requirements_path: requirements.yml

verifier:
  name: inspec

suites:
  - name: default
#   driver_config:
#      forward:
#        - 80:9080
