---
driver:
  name: docker

platforms:
  - name: centos
    driver_config:
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
  - name: amazonlinux-2-docker
    driver_config:
      platform: rhel
      image: amazonlinux:2
      run_command: /usr/sbin/init
      privileged: true
      # Apply workaround in that the ps command is not working out of the box
      # on Amazon Linux 2 Docker containers
      provision_command:
        - yum -y install procps-ng
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
  - name: amazonlinux-2-ec2
    driver:
      name: ec2
    driver_config:
      instance_type: m1.small
      aws_ssh_key_id: my-dev-key 
      region: us-west-2
      image_id: ami-8f08bcf7
      availability_zone: us-west-2b
      subnet_id: subnet-fd415ab5
      associate_public_ip: false
      security_group_ids:
        - sg-0ae9bda9a4b3fa381
      interface: dns
      tags:
        Name: tk-ansible-role-realm-object-server
        Created-By: Test Kitchen
    transport:
      username: ec2-user
      ssh_key: ~/my-dev-key.pem
    provisioner:
      name: ansible_playbook
      #require_pip: true
  - name: amazonlinux-1-ec2
    driver:
      name: ec2
    driver_config:
      instance_type: m1.small
      aws_ssh_key_id: my-dev-key 
      region: us-west-2
      image_id: ami-f2d3638a
      availability_zone: us-west-2b
      subnet_id: subnet-fd415ab5
      associate_public_ip: false
      security_group_ids:
        - sg-0ae9bda9a4b3fa381
      interface: dns
      tags:
        Name: tk-ansible-role-realm-object-server
        Created-By: Test Kitchen
    transport:
      username: ec2-user
      ssh_key: ~/my-dev-key.pem
    provisioner:
      name: ansible_playbook
      #require_pip: true

provisioner:
  name: ansible_playbook
  hosts: localhost
  ansible_verbose: false
  ansible_verbosity: :debug
  require_chef_for_busser: false
  require_ruby_for_busser: false
  requirements_path: requirements.yml

verifier:
  name: serverspec

suites:
  - name: default
#   driver_config:
#      forward:
#        - 80:9080
